In [1]:
import pandas as pd
import numpy as np

In [ ]:
# 1) Charger
df = pd.read_csv("../data/raw/daily_sales_french_bakery.csv")

# 2) Date
df["ds"] = pd.to_datetime(df["ds"])
df = df.sort_values("ds").set_index("ds")

# 3) Série globale journalière
daily_sales = df.groupby(df.index)["y"].sum().asfreq("D")
daily_sales = daily_sales.fillna(0) 
daily_sales.head()

ds
2021-01-02     987.85
2021-01-03    1014.30
2021-01-04     461.90
2021-01-05     515.70
2021-01-06       0.00
Freq: D, Name: y, dtype: float64

In [3]:
data = daily_sales.to_frame(name="y")
data.head()

                  y
ds
2021-01-02   987.85
2021-01-03  1014.30
2021-01-04   461.90
2021-01-05   515.70
2021-01-06     0.00

In [4]:
data["day_of_week"] = data.index.dayofweek          # 0=lundi ... 6=dimanche
data["month"] = data.index.month
data["day_of_month"] = data.index.day
data["week_of_year"] = data.index.isocalendar().week.astype(int)
data["is_weekend"] = (data["day_of_week"] >= 5).astype(int)

data.head()

,y,day_of_week,month,day_of_month,week_of_year,is_weekend
ds,,,,,,
2021-01-02,987.85,5,1,2,53,1
2021-01-03,1014.30,6,1,3,53,1
2021-01-04,461.90,0,1,4,1,0
2021-01-05,515.70,1,1,5,1,0
2021-01-06,0.00,2,1,6,1,0

In [5]:
data["lag_1"] = data["y"].shift(1)
data["lag_7"] = data["y"].shift(7)
data["lag_14"] = data["y"].shift(14)

In [6]:
data["roll_mean_7"] = data["y"].rolling(7).mean()
data["roll_std_7"] = data["y"].rolling(7).std()
data["roll_mean_30"] = data["y"].rolling(30).mean()

In [7]:
data = data.dropna()
data.head(), data.shape

(                 y  day_of_week  month  day_of_month  week_of_year  \
 ds
 2021-01-31  779.95            6      1            31             4
 2021-02-01  340.40            0      2             1             5
 2021-02-02  411.35            1      2             2             5
 2021-02-03    0.00            2      2             3             5
 2021-02-04  424.55            3      2             4             5

             is_weekend   lag_1   lag_7  lag_14  roll_mean_7  roll_std_7  \
 ds
 2021-01-31           1  571.15  761.85  834.20   447.207143  235.653099
 2021-02-01           0  779.95  438.30  451.05   433.221429  239.149021
 2021-02-02           0  340.40  431.05  416.35   430.407143  239.294702
 2021-02-03           0  411.35    0.00    0.00   430.407143  239.294702
 2021-02-04           0    0.00  397.30  441.00   434.300000  238.887655

             roll_mean_30
 ds
 2021-01-31    508.622333
 2021-02-01    487.040667
 2021-02-02    466.942333
 2021-02-03    451.545667
 2021-02-04    448.507333  ,
 (608, 12))

In [8]:
data.to_csv("../data/processed/features_daily_sales.csv")
print("Fichier sauvegardé : data/processed/features_daily_sales.csv")

Fichier sauvegardé : data/processed/features_daily_sales.csv